# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('onesta', 'Onesta'), ('cecilia', 'Cecilia'), ('priscilla', 'Priscilla'), ('lily', 'Lily Mae'), ('curly', 'Curly'), ('ophelia', 'Ophelia'), ('abby', 'Abby')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='rsvp',
            name='member',
            field=models.ManyToManyField(to='rsvp.Member'),
        ),
    ]
