# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20161213_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='member',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='member',
            field=models.CharField(choices=[('onesta', 'Onesta'), ('cecilia', 'Cecilia'), ('priscilla', 'Priscilla'), ('lily', 'Lily Mae'), ('curly', 'Curly'), ('ophelia', 'Ophelia'), ('abby', 'Abby')], default='unknown', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
