# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20161213_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
