# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_auto_20161213_2131'),
        ('rsvp', '0007_auto_20161213_2225'),
    ]

    operations = [
    ]
