# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='member',
            field=models.CharField(choices=[('onesta', 'Onesta'), ('cecilia', 'Cecilia'), ('priscilla', 'Priscilla'), ('lily', 'Lily Mae'), ('curly', 'Curly'), ('ophelia', 'Ophelia'), ('abby', 'Abby')], max_length=50),
        ),
    ]
